
void lcd_init(void);
void lcd_set_pixel(unsigned int x, unsigned int y, unsigned int color);
unsigned int lcd_get_pixel(unsigned int x, unsigned int y);
void lcd_clear_screen(unsigned int color);
void lcd_rect_fill(int x0, int y0, int x1, int y1,int color);
void lcd_draw_char(unsigned char c);
void lcd_set_backcolor(unsigned int backcolor);
void lcd_set_fontcolor(unsigned int fontcolor);


#define LightPink            0xFFB6C1   //浅粉红
#define Pink                 0xFFC0CB   //粉红
#define Crimson              0xDC143C   //猩红(深红)
#define LavenderBlush        0xFFF0F5   //淡紫红
#define PaleVioletRed        0xDB7093   //弱紫罗兰红
#define HotPink              0xFF69B4   //热情的粉红
#define DeepPink             0xFF1493   //深粉红
#define MediumVioletRed      0xC71585   //中紫罗兰红
#define Orchid               0xDA70D6   //兰花紫
#define Thistle              0xD8BFD8   //蓟
#define Plum                 0xDDA0DD   //李子紫
#define Violet               0xEE82EE   //紫罗兰
#define Magenta              0xFF00FF   //洋红(品红 玫瑰红)
#define DarkMagenta          0x8B008B   //深洋红
#define Purple               0x800080   //紫色
#define MediumOrchid         0xBA55D3   //中兰花紫
#define DarkViolet           0x9400D3   //暗紫罗兰
#define DarkOrchid           0x9932CC   //暗兰花紫
#define Indigo               0x4B0082   //靛青 (紫兰色)
#define BlueViolet           0x8A2BE2   //蓝紫罗兰
#define MediumPurple         0x9370DB   //中紫色
#define MediumSlateBlue      0x7B68EE   //中板岩蓝
#define SlateBlue            0x6A5ACD   //板岩蓝
#define DarkSlateBlue        0x483D8B   //暗板岩蓝
#define Lavender             0xE6E6FA   //熏衣草淡紫
#define GhostWhite           0xF8F8FF   //幽灵白
#define Blue                 0x0000FF   //纯蓝
#define MediumBlue           0x0000CD   //中蓝色
#define MidnightBlue         0x191970   //午夜蓝
#define DarkBlue             0x00008B   //暗蓝色
#define Navy                 0x000080   //海军蓝
#define RoyalBlue            0x4169E1   //皇家蓝 (宝蓝)
#define CornflowerBlue       0x6495ED   //矢车菊蓝
#define LightSteelBlue       0xB0C4DE   //亮钢蓝
#define LightSlateGray       0x778899   //亮石板灰
#define SlateGray            0x708090   //石板灰
#define DodgerBlue           0x1E90FF   //道奇蓝
#define AliceBlue            0xF0F8FF   //爱丽丝蓝
#define SteelBlue            0x4682B4   //钢蓝 (铁青)
#define LightSkyBlue         0x87CEFA   //亮天蓝色  
#define SkyBlue              0x87CEEB   //天蓝色
#define DeepSkyBlue          0x00BFFF   //深天蓝
#define LightBlue            0xADD8E6   //亮蓝
#define PowderBlue           0xB0E0E6   //火药青
#define CadetBlue            0x5F9EA0   //军服蓝
#define Azure                0xF0FFFF   //蔚蓝色
#define LightCyan            0xE0FFFF   //淡青色
#define PaleTurquoise        0xAFEEEE   //弱绿宝石
#define Cyan                 0x00FFFF   //青色
#define DarkTurquoise        0x00CED1   //暗绿宝石
#define DarkSlateGray        0x2F4F4F   //暗石板灰
#define DarkCyan             0x008B8B   //暗青色
#define Teal                 0x008080   //水鸭色   
#define MediumTurquoise      0x48D1CC   //中绿宝石
#define LightSeaGreen        0x20B2AA   //浅海洋绿
#define Turquoise            0x40E0D0   //绿宝石
#define Aquamarine           0x7FFFD4   //宝石碧绿
#define MediumAquamarine     0x66CDAA   //中宝石碧绿
#define MediumSpringGreen    0x00FA9A   //中春绿色
#define MintCream            0xF5FFFA   //薄荷奶油
#define SpringGreen          0x00FF7F   //春绿色
#define MediumSeaGreen       0x3CB371   //中海洋绿
#define SeaGreen             0x2E8B57   //海洋绿
#define Honeydew             0xF0FFF0   //蜜瓜色
#define LightGreen           0x90EE90   //淡绿色
#define PaleGreen            0x98FB98   //弱绿色
#define DarkSeaGreen         0x8FBC8F   //暗海洋绿
#define LimeGreen            0x32CD32   //闪光深绿
#define Lime                 0x00FF00   //闪光绿
#define ForestGreen          0x228B22   //森林绿
#define Green                0x008000   //纯绿
#define DarkGreen            0x006400   //暗绿色
#define Chartreuse           0x7FFF00   //查特酒绿
#define LawnGreen            0x7CFC00   //草坪绿
#define GreenYellow          0xADFF2F   //绿黄色
#define DarkOliveGreen       0x556B2F   //暗橄榄绿
#define YellowGreen          0x9ACD32   //黄绿色
#define OliveDrab            0x6B8E23   //橄榄褐色
#define Beige                0xF5F5DC   //灰棕色
#define LightGoldenrodYellow 0xFAFAD2   //亮菊黄
#define Ivory                0xFFFFF0   //象牙
#define LightYellow          0xFFFFE0   //浅黄色
#define Yellow               0xFFFF00   //纯黄
#define Olive                0x808000   //橄榄
#define DarkKhaki            0xBDB76B   //深卡叽布
#define LemonChiffon         0xFFFACD   //柠檬绸
#define PaleGoldenrod        0xEEE8AA   //灰菊黄
#define Khaki                0xF0E68C   //卡叽布
#define Gold                 0xFFD700   //金色
#define Cornsilk             0xFFF8DC   //玉米丝色
#define Goldenrod            0xDAA520   //金菊黄
#define DarkGoldenrod        0xB8860B   //暗金菊黄
#define FloralWhite          0xFFFAF0   //花的白色  
#define OldLace              0xFDF5E6   //旧蕾丝
#define Wheat                0xF5DEB3   //小麦色
#define Moccasin             0xFFE4B5   //鹿皮靴
#define Orange               0xFFA500   //橙色
#define PapayaWhip           0xFFEFD5   //番木瓜
#define BlanchedAlmond       0xFFEBCD   //发白杏仁色
#define NavajoWhite          0xFFDEAD   //土著白
#define AntiqueWhite         0xFAEBD7   //古董白
#define Tan                  0xD2B48C   //茶色
#define BurlyWood            0xDEB887   //硬木色
#define Bisque               0xFFE4C4   //陶坯黄
#define DarkOrange           0xFF8C00   //深橙色
#define Linen                0xFAF0E6   //亚麻布
#define Peru                 0xCD853F   //秘鲁
#define PeachPuff            0xFFDAB9   //桃肉色
#define SandyBrown           0xF4A460   //沙棕色
#define Chocolate            0xD2691E   //巧克力
#define SaddleBrown          0x8B4513   //马鞍棕色
#define Seashell             0xFFF5EE   //海贝壳
#define Sienna               0xA0522D   //黄土赭色
#define LightSalmon          0xFFA07A   //浅鲑鱼肉色
#define Coral                0xFF7F50   //珊瑚
#define OrangeRed            0xFF4500   //橙红色
#define DarkSalmon           0xE9967A   //深鲜肉色
#define Tomato               0xFF6347   //番茄红
#define MistyRose            0xFFE4E1   //薄雾玫瑰
#define Salmon               0xFA8072   //鲜肉色
#define Snow                 0xFFFAFA   //雪
#define LightCoral           0xF08080   //淡珊瑚色
#define RosyBrown            0xBC8F8F   //玫瑰棕色
#define IndianRed            0xCD5C5C   //印度红
#define Red                  0xFF0000   //纯红
#define Brown                0xA52A2A   //棕色
#define FireBrick            0xB22222   //耐火砖
#define DarkRed              0x8B0000   //深红色
#define Maroon               0x800000   //栗色
#define White                0xFFFFFF   //纯白
#define WhiteSmoke           0xF5F5F5   //白烟
#define Gainsboro            0xDCDCDC   //庚斯博罗灰色
#define LightGrey            0xD3D3D3   //浅灰色
#define Silver               0xC0C0C0   //银灰色
#define DarkGray             0xA9A9A9   //深灰色
#define Gray                 0x808080   //灰色
#define DimGray              0x696969   //暗淡的灰色
#define Black                0x000000   //纯黑


